In [4]:
import numpy as np
import pandas as pd

In [5]:
Array1 = np.array([10,20,30,40,50])

In [6]:
print("Numpy Array")
print(Array1)

Numpy Array
[10 20 30 40 50]


In [7]:
print("Shape of the Array:",Array1.shape)

Shape of the Array: (5,)


In [8]:
marks=pd.Series([100,200,300,400,500])


In [9]:
print("\n Pandas Series:",marks)


 Pandas Series: 0    100
1    200
2    300
3    400
4    500
dtype: int64


In [11]:
array_di=np.array([11,12,13,14,15,16,17,18,19,20])
print("\n N1-dIMENSIONAL Numpy Array:",array_di)


 N1-dIMENSIONAL Numpy Array: [11 12 13 14 15 16 17 18 19 20]


In [12]:
array_2=np.array([[1,2,3]
                ,[4,5,6]
                 ])
print("\n multiDimenstionl numpy Array:",array_2)


 multiDimenstionl numpy Array: [[1 2 3]
 [4 5 6]]


In [13]:
zeros_array=np.zeros((4,5))
print("/n Zeros Arrqay:",zeros_array)

/n Zeros Arrqay: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
ones_array=np.ones((5,4))
print("\n Ones Array:",ones_array)


 Ones Array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
